name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: make install-deps

      - name: Build application
        run: make build

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: antizapret-admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
